const menu = [
  {
    id: 1,
    title: 'Menues',
    category: 'React.js',
    goto: `'let's see'`,
    // img: './images/item-1.jpeg',
    img: require('./images/ourmenu.jpeg'),
    desc: `Designed to display the menu of a food and beverage establishment, allowing users to explore the different items available and obtain relevant information about each one of them. `,
  },
  {
    id: 2,
    title: 'Our Reviews',
    category: 'React.js',
    goto: `'let's see'`,
    img: require('./images/ourreviews.jpeg'),
    desc: `Here users can explore and read testimonials from different people. It could be used in a variety of contexts, such as testimonials from satisfied customers, work experiences, product or service reviews, among others. `,
  },
  {
    id: 3,
    title: 'Little Lemon App',
    category: 'React Native',
    goto: `'let's see'`,
    img: require('./images/lemonRN.jpg'),
    desc: `An app that offers detailed information about a restaurant. It shows a complete menu organized in categories, obtained from a database. In addition, it offers users the ability to create personal profiles, where they can view and edit their personal information.
    Saving the data on the user's device, allowing faster and more efficient access in future sessions.`,
  },
  {
    id: 4,
    title: 'La Fe De Jesus',
    category: 'React Native',
    goto: `'let's see'`,
    img: require('./images/fedejesus.jpg'),
    desc: `An interactive learning platform that allows users to navigate between different lessons, save their progress, and perform educational activities.`,
  },
  {
    id: 5,
    title: 'Lil Lemon Web',
    category: 'React.js',
    goto: `'let's see'`,
    img: require('./images/mylilLemon.jpeg'),
    desc: `Designed to facilitate the reservation of tables in a restaurant. It provides an interface where users can select the date, number of guests and the occasion of the reservation, and then make the reservation with one click. A management of reservations and confirmations is also used.`,
  },
  {
    id: 6,
    title: 'Stripe',
    category: 'React.js',
    goto: `'let's see'`,
    img: require('./images/stripes.jpeg'),
    desc: `An online payment platform like Stripe. Its main objective would be to provide a reliable and secure payment infrastructure for companies and businesses of different sizes of operations, allowing them to accept payments online, make payments and manage their merchants efficiently.`,
  },
  // {
  //   id: 7,
  //   title: 'bacon overflow',
  //   category: 'breakfast',
  //   goto: `'let's see'`,
  //   img: require('./images/item-7.jpeg'),
  //   desc: `carry jianbing normcore freegan. Viral single-origin coffee live-edge, pork belly cloud bread iceland put a bird `,
  // },
  // {
  //   id: 8,
  //   title: 'american classic',
  //   category: 'lunch',
  //   goto: `'let's see'`,
  //   img: require('./images/item-8.jpeg'),
  //   desc: `on it tumblr kickstarter thundercats migas everyday carry squid palo santo leggings. Food truck truffaut  `,
  // },
];
export default menu;
